name: Build Kivy APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Download a single artifact
        uses: actions/download-artifact@v4
        with:
          name: my-artifact

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            python3-pip \
            python3-setuptools \
            python3-dev \
            git \
            zip \
            unzip \
            openjdk-17-jdk \
            zlib1g-dev \
            libncurses5 \
            libncurses5-dev \
            libtinfo6 \
            libtinfo-dev \
            libffi-dev \
            libssl-dev \
            autoconf \
            libtool \
            pkg-config \
            cmake

      - name: Upgrade pip
        run: |
          python3 -m pip install --upgrade pip

      - name: Install Buildozer
        run: |
          pip install --upgrade Cython==0.29.36
          pip install --upgrade buildozer

      - name: Initialize Buildozer (if needed)
        run: |
          if [ ! -f buildozer.spec ]; then
            buildozer init
          fi

      - name: Build APK
        run: |
          buildozer android debug

      - name: Upload APK artifact
        uses: upload-artifact@v4
        with:
          name: kivy-apk
          path: bin/*.apk
